import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { api } from '../api';

function statusClass(status) { return status.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, ''); }

const DAY_MESSAGES = {
  Holiday: 'Holiday - Hospital Closed.',
  'My Upcoming Appointment': 'You already have an upcoming appointment with this doctor on this date.',
  'Previous Visit': 'This is a previous visit date.',
  'Visited – Appointment Not Completed': 'Your previous appointment on this date was not completed. Please select another available date to book a new appointment.',
};

export default function CalendarPage() { const { doctorId } = useParams(); const navigate = useNavigate(); const [doctor, setDoctor] = useState(null); const [calendar, setCalendar] = useState([]); const [slots, setSlots] = useState([]); const [date, setDate] = useState(''); const [error, setError] = useState(''); useEffect(() => { Promise.all([api(`/doctors/${doctorId}`), api(`/appointments/calendar/${doctorId}`)]).then(([d, c]) => { setDoctor(d); setCalendar(c); }).catch((err) => setError(err.message)); }, [doctorId]); async function selectDay(day) { if (day.status !== 'Available') return setError(DAY_MESSAGES[day.status] || 'This date is not available.'); setDate(day.date); setError(''); try { const data = await api(`/appointments/available-slots/${doctorId}/${day.date}`); setSlots(data.slot_options || data.available_slots.map((time) => ({ time, available: true, reason: null }))); } catch (err) { setError(err.message); } } function continueBooking(time) { localStorage.setItem('booking_draft', JSON.stringify({ doctorId: Number(doctorId), doctor, date, time })); navigate('/book-appointment'); } return <div className="container page"><Link to={`/doctors/${doctorId}`} className="muted">← Back to Doctor Profile</Link><div className="eyebrow">Select date and time</div><h1 className="page-title">Calendar & Slot Selection</h1>{error && <div className="message error">{error}</div>}<div className="calendar-legend"><span className="legend-dot available"></span>Available<span className="legend-dot full"></span>Full<span className="legend-dot holiday"></span>Holiday<span className="legend-dot my-upcoming-appointment"></span>My Upcoming Appointment<span className="legend-dot previous-visit"></span>Previous Visit<span className="legend-dot visited-appointment-not-completed"></span>Visited – Not Completed</div><div className="calendar-layout"><section className="panel calendar-card"><h2>{doctor?.full_name || 'Doctor'}</h2><div className="calendar-grid-react">{calendar.map((day) => <button className={`calendar-day-react ${statusClass(day.status)}`} key={day.date} onClick={() => selectDay(day)}><strong>{day.date.slice(5)}</strong><small>{day.status}</small>{day.status === 'Available' && <span>{day.booked}/10</span>}</button>)}</div></section><aside className="panel slot-panel"><h2>Available Time Slots</h2>{date && <p className="muted">{date}</p>}{slots.map((slot) => <button className={`slot-button ${slot.available ? '' : 'disabled'}`} key={slot.time} disabled={!slot.available} onClick={() => continueBooking(slot.time)}>{slot.time} <span>{slot.available ? 'Available' : slot.reason}</span></button>)}{date && !slots.some((slot) => slot.available) && <p className="muted">No slots available.</p>}</aside></div></div>; }
